name: Python Flask App CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start Flask app and test
        run: |
          python app.py &
          sleep 5
          if ! curl -s http://127.0.0.1:5000 | grep -q "Team Name Generator"; then
            echo "Erreur : Le serveur Flask ne répond pas correctement"
            cat flask.log
            exit 1
          fi
          pkill -f "app.py" || true 