name: Python Flask App CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test generator script
      run: python app.py

    - name: Start Flask app and test
      run: |
        python app.py &
        sleep 5  # Attend que Flask démarre
        curl -s http://127.0.0.1:5000 | grep -q "Team Name Generator"
        pkill -f "app.py"  # Tue le processus Flask après le test
